version: '3.1'
services:
  stats-server:
    build: ./stat-svc/stat-server
    image: stat-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=events
      - DB_HOST=stats-db
      - DB_PORT=5432
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=events
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./main-svc
    image: main-svc
    container_name: main-svc
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - statistic-server.uri=http://stats-server:9090
      - app-name=ewm-main-service


  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=events_main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root